# fc-list : family style


[font]
normal = { family = "Noto Sans Mono"}
##normal = { family = "Liberation Mono"}
size = 6.0

[colors.primary]
  # Default colors
background =  '#1f1f1f'
foreground =  '#f8f8f8'

  # Normal colors
[colors.normal]
black =  '#1f1f1f'
red =    '#d81765'
green =  '#97d01a'
yellow = '#ffa800'
blue   = '#16b1fb'
magenta= '#ff2491'
cyan=    '#0fdcb6'
white=   '#ebebeb'

  # Bright colors
[colors.bright]
black =   '#38252c'
red =     '#ff0000'
green =   '#76b639'
yellow =  '#e1a126'
blue =    '#289cd5'
magenta = '#ff2491'
cyan =    '#0a9b81'
white =   '#f8f8f8'
